version: "3.1"
services:    
    interest-rate-api:
        container_name: interest-rate-api
        image: interest-rate-api
        restart: always
        networks:
            - interest-network
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
        build:
            context: ../backend/
            dockerfile: InterestRate/Dockerfile
        ports:
            - "5033:80"
    interest-calculation-api:
        container_name: interest-calculation-api
        image: interest-calculation-api
        restart: always
        networks:
            - interest-network
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
        build:
            context: ../backend/
            dockerfile: InterestCalculation/Dockerfile
        ports:
            - "5034:80"
networks:
  interest-network:
    driver: bridge
